apiVersion: v1
kind: Secret
metadata:
  name: pgpassword
data:
  POSTGRES_PASSWORD: <pg-password-b64encode>

---
apiVersion: v1
kind: Secret
metadata:
  name: gs-credentials
type: Opaque
data:
  google_secret.json: <credentials-b64encode>
